<?php

namespace frontend\modules\data\models;

use common\models\Currency as BaseModel;
use yii\behaviors\TimestampBehavior;

class Currency extends BaseModel
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => time(),
            ],
        ]); // TODO: Change the autogenerated stub
    }
}
