<?php

namespace frontend\modules\data\models;

use common\models\Shop as BaseModel;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;

class Shop extends BaseModel
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => time(),
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @return ActiveQuery
     */
    public function getCurrency()
    {
        return $this->hasOne(Currency::class, ['id' => 'currency_id']);
    }
}
